-- =========================================================
-- BACKLOX UNIVERSE — SUPABASE POSTGRESQL DATABASE SCHEMA
-- =========================================================

-- 1. Users Table
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT,
  role TEXT DEFAULT 'trainee' CHECK (role IN ('trainee', 'instructor')),
  is_premium BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Courses Table
CREATE TABLE IF NOT EXISTS public.courses (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  instructor_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  instructor_name TEXT,
  category TEXT,
  stream_id TEXT,
  branch_id TEXT,
  level TEXT DEFAULT 'Intermediate',
  price NUMERIC DEFAULT 0,
  original_price NUMERIC DEFAULT 0,
  video_duration TEXT,
  trailer_video_url TEXT,
  trailer_image TEXT,
  description TEXT,
  status TEXT DEFAULT 'published',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Course Modules Table
CREATE TABLE IF NOT EXISTS public.course_modules (
  id TEXT PRIMARY KEY,
  course_id TEXT REFERENCES public.courses(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  duration TEXT,
  video_url TEXT,
  resource_url TEXT,
  is_free_preview BOOLEAN DEFAULT FALSE,
  position INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Course Enrollments Table
CREATE TABLE IF NOT EXISTS public.course_enrollments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  course_id TEXT REFERENCES public.courses(id) ON DELETE CASCADE,
  enrolled_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, course_id)
);

-- 5. Payments Table
CREATE TABLE IF NOT EXISTS public.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  razorpay_order_id TEXT UNIQUE NOT NULL,
  razorpay_payment_id TEXT UNIQUE,
  amount NUMERIC NOT NULL,
  currency TEXT DEFAULT 'INR',
  status TEXT DEFAULT 'created',
  plan TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Trainee Progress Table
CREATE TABLE IF NOT EXISTS public.trainee_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  course_id TEXT,
  module_id TEXT,
  completed BOOLEAN DEFAULT FALSE,
  score NUMERIC DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, course_id, module_id)
);

-- 7. Assessment Results Table
CREATE TABLE IF NOT EXISTS public.quiz_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  stream_id TEXT,
  exam_id TEXT,
  total_questions INTEGER,
  correct_answers INTEGER,
  score_percentage NUMERIC,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) policies
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

-- Public read policies for published courses
CREATE POLICY "Public courses are viewable by everyone" ON public.courses
  FOR SELECT USING (status = 'published');

CREATE POLICY "Public modules are viewable by everyone" ON public.course_modules
  FOR SELECT USING (true);
