// Backlox Master Aptitude Question Bank
// Sourced from TCS NQT, Infosys, CAT, GATE, UPSC CSAT, Bank PO, NEET, and Technical Placement tests

export const APTITUDE_CATEGORIES = [
  { id: "all", name: "All Domains (Unified Aptitude Matrix)" },
  { id: "quant", name: "Quantitative Aptitude & Mathematics" },
  { id: "logical", name: "Logical & Analytical Reasoning" },
  { id: "verbal", name: "Verbal Ability & English Comprehension" },
  { id: "tech", name: "Computer Science & Technical Aptitude" },
  { id: "medical", name: "Clinical & Medical Sciences" },
  { id: "commerce", name: "Commerce, Finance & Legal Reasoning" },
];

export const MASTER_APTITUDE_BANK = [
  // =========================================================================
  // 1. QUANTITATIVE APTITUDE (Arithmetic, Algebra, Modern Math, Geometry)
  // =========================================================================
  {
    id: "q-1",
    category: "quant",
    subject: "Time & Work",
    difficulty: "Standard",
    question: "A can complete a project in 12 days, and B can complete the same project in 18 days. They work together for 4 days, after which A leaves. In how many additional days will B complete the remaining work?",
    options: ["8 days", "6 days", "10 days", "7 days"],
    answer: 0,
    formula: "Work done in t days = t * (1/A + 1/B); Remaining Work = 1 - (Work done)",
    explanation: "Combined 1-day rate = 1/12 + 1/18 = 5/36. In 4 days, work completed = 4 * (5/36) = 20/36 = 5/9. Remaining work = 1 - 5/9 = 4/9. Time required for B alone = (4/9) / (1/18) = (4/9) * 18 = 8 days.",
  },
  {
    id: "q-2",
    category: "quant",
    subject: "Time, Speed & Distance",
    difficulty: "Standard",
    question: "A train traveling at 72 km/h crosses a 200-meter long platform in 22 seconds. What is the length of the train?",
    options: ["240 meters", "200 meters", "220 meters", "260 meters"],
    answer: 0,
    formula: "Speed in m/s = Speed in km/h * (5/18); Total Distance = Length of Train + Length of Platform = Speed * Time",
    explanation: "Speed in m/s = 72 * (5/18) = 20 m/s. Total distance covered in 22 s = 20 m/s * 22 s = 440 m. Since Total Distance = (Train Length) + 200 m, Train Length = 440 - 200 = 240 meters.",
  },
  {
    id: "q-3",
    category: "quant",
    subject: "Permutations & Combinations",
    difficulty: "Standard",
    question: "In how many distinct ways can the letters of the word 'LEADER' be arranged such that vowels always occur together?",
    options: ["72", "144", "240", "48"],
    answer: 0,
    formula: "Number of arrangements = (Grouped Items)! / (Repetitions) * (Internal Vowel Arrangements) / (Vowel Repetitions)",
    explanation: "Vowels in LEADER: E, A, E (3 vowels, with E repeated twice). Consonants: L, D, R (3 consonants). Treat vowels as a single block: 4 units (L, D, R, [EAE]). Permutations of 4 units = 4! = 24. Internal arrangements of [EAE] = 3! / 2! = 3. Total ways = 24 * 3 = 72.",
  },
  {
    id: "q-4",
    category: "quant",
    subject: "Probability Theory",
    difficulty: "Standard",
    question: "Two fair six-sided dice are rolled simultaneously. What is the probability that the sum of the numbers obtained is a prime number?",
    options: ["5/12", "7/18", "1/2", "13/36"],
    answer: 0,
    formula: "P(E) = n(E) / n(S); Sample Space n(S) = 36",
    explanation: "Possible sums range from 2 to 12. Prime sums: 2, 3, 5, 7, 11.\nSum 2: (1,1) [1 way]\nSum 3: (1,2), (2,1) [2 ways]\nSum 5: (1,4), (2,3), (3,2), (4,1) [4 ways]\nSum 7: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1) [6 ways]\nSum 11: (5,6), (6,5) [2 ways]\nTotal favorable outcomes = 1 + 2 + 4 + 6 + 2 = 15.\nP = 15 / 36 = 5 / 12.",
  },
  {
    id: "q-5",
    category: "quant",
    subject: "Compound Interest & Growth",
    difficulty: "Standard",
    question: "A sum of money doubles itself in 4 years under compound interest compounded annually. In how many years will it become 8 times of itself at the same rate?",
    options: ["12 years", "16 years", "8 years", "10 years"],
    answer: 0,
    formula: "If amount becomes 2^k times, Time = k * t",
    explanation: "At compound interest, if A = P*(1+r)^t = 2P in 4 years, then (1+r)^4 = 2. To become 8 times (2^3), we need (1+r)^T = 8 = 2^3 = ((1+r)^4)^3 = (1+r)^12. Therefore, T = 12 years.",
  },
  {
    id: "q-6",
    category: "quant",
    subject: "Profit, Loss & Discount",
    difficulty: "Standard",
    question: "A merchant marks his goods 40% above the cost price and allows a discount of 15% on the marked price. What is his net profit percentage?",
    options: ["19%", "25%", "17.5%", "21%"],
    answer: 0,
    formula: "Net % Change = a + b + (ab/100), where a = +40 and b = -15",
    explanation: "Let CP = 100. MP = 140. Discount = 15% of 140 = 21. SP = 140 - 21 = 119. Profit = SP - CP = 119 - 100 = 19%. Using formula: 40 - 15 - (40*15/100) = 25 - 6 = 19%.",
  },
  {
    id: "q-7",
    category: "quant",
    subject: "Pipes & Cisterns",
    difficulty: "Standard",
    question: "Pipe A can fill a tank in 20 hours, and Pipe B can fill it in 30 hours. A waste pipe C can empty the full tank in 40 hours. If all three pipes are opened together, how long will it take to fill the empty tank?",
    options: ["17 hours 8 minutes (120/7 hrs)", "15 hours", "18 hours 30 minutes", "16 hours 40 minutes"],
    answer: 0,
    formula: "Net 1-hour rate = 1/A + 1/B - 1/C",
    explanation: "Net rate = 1/20 + 1/30 - 1/40. LCM of (20, 30, 40) = 120. Net rate = (6 + 4 - 3)/120 = 7/120. Time to fill = 120 / 7 hours = 17 hours and 8.5 minutes.",
  },
  {
    id: "q-8",
    category: "quant",
    subject: "Modular Arithmetic & Number Theory",
    difficulty: "Competitive",
    question: "What is the remainder when (7^101 + 5) is divided by 8?",
    options: ["4", "6", "2", "0"],
    answer: 0,
    formula: "7 ≡ -1 (mod 8) => 7^n ≡ (-1)^n (mod 8)",
    explanation: "7 ≡ -1 (mod 8). Therefore, 7^101 ≡ (-1)^101 ≡ -1 (mod 8). Then (7^101 + 5) ≡ -1 + 5 ≡ 4 (mod 8). The remainder is 4.",
  },
  {
    id: "q-9",
    category: "quant",
    subject: "Averages & Mixtures",
    difficulty: "Standard",
    question: "In what ratio must a grocer mix tea at ₹60/kg and ₹65/kg so that by selling the mixture at ₹68.20/kg he may gain 10%?",
    options: ["3 : 2", "2 : 3", "4 : 1", "5 : 3"],
    answer: 0,
    formula: "Mean Cost Price = SP / (1 + Profit%); Rule of Alligation: (Cheaper / Dearer) = (Price of Dearer - Mean) / (Mean - Price of Cheaper)",
    explanation: "Selling price = ₹68.20 with 10% profit. Mean CP = 68.20 / 1.10 = ₹62/kg. Using Alligation: Cheaper (60) vs Dearer (65), Mean (62). (65 - 62) / (62 - 60) = 3 / 2. Ratio is 3 : 2.",
  },
  {
    id: "q-10",
    category: "quant",
    subject: "Geometric Progressions",
    difficulty: "Competitive",
    question: "The sum of an infinite geometric progression is 16, and the sum of their squares is 153.6. What is the common ratio (r) of the series?",
    options: ["1/4", "1/2", "3/5", "2/3"],
    answer: 0,
    formula: "S_inf = a / (1 - r) = 16; S_sq = a^2 / (1 - r^2) = 153.6",
    explanation: "a = 16(1-r). Squaring: a^2 = 256(1-r)^2. Then S_sq = 256(1-r)^2 / [(1-r)(1+r)] = 256(1-r)/(1+r) = 153.6. (1-r)/(1+r) = 153.6 / 256 = 0.6 = 3/5. 5(1-r) = 3(1+r) => 5 - 5r = 3 + 3r => 8r = 2 => r = 1/4.",
  },

  // =========================================================================
  // 2. LOGICAL & ANALYTICAL REASONING (Syllogisms, Blood Relations, Arrangements)
  // =========================================================================
  {
    id: "l-1",
    category: "logical",
    subject: "Syllogisms & Deductive Logic",
    difficulty: "Standard",
    question: "Statements:\n1. All algorithms are models.\n2. Some models are neural nets.\n3. All neural nets are differentiable.\nConclusions:\nI. Some differentiable entities are models.\nII. Some algorithms are neural nets.",
    options: [
      "Only Conclusion I follows",
      "Only Conclusion II follows",
      "Both Conclusion I and II follow",
      "Neither Conclusion I nor II follows",
    ],
    answer: 0,
    formula: "Transitivity: Some Models are Neural Nets + All Neural Nets are Differentiable => Some Models are Differentiable",
    explanation: "Since some models are neural nets, and all neural nets are differentiable, the intersection of models and differentiable entities is non-empty (Conclusion I holds). However, no direct relation between algorithms and neural nets is guaranteed (Conclusion II does not follow).",
  },
  {
    id: "l-2",
    category: "logical",
    subject: "Blood Relations",
    difficulty: "Standard",
    question: "Pointing to a photograph of a man, Vikram says: 'His mother is the only daughter of my mother.' How is Vikram related to the man in the photograph?",
    options: ["Maternal Uncle", "Father", "Brother", "Grandfather"],
    answer: 0,
    formula: "Vikram's mother's only daughter = Vikram's sister; Sister's son => Vikram is Maternal Uncle",
    explanation: "The 'only daughter of my mother' is Vikram's sister. The man's mother is Vikram's sister. Therefore, Vikram is the maternal uncle (Mama) of the man.",
  },
  {
    id: "l-3",
    category: "logical",
    subject: "Circular Seating Arrangement",
    difficulty: "Competitive",
    question: "Eight people (A, B, C, D, E, F, G, H) are sitting in a circle facing the center. A sits 3rd to the left of B, who is 2nd to the right of G. H sits opposite to D. F is an immediate neighbor of A and C. Who sits directly opposite to A?",
    options: ["E", "G", "B", "H"],
    answer: 0,
    formula: "Position indexing modulo 8 in counter-clockwise circular layout",
    explanation: "Arranging modulo 8: Fix B at position 0. A sits 3rd left (position 5). G is 2nd left of B (position 6). D and H are opposite (differ by 4). F is between A and C (position 4, with C at 3). Resolving remaining slots leaves E at position 1, directly opposite position 5 (A).",
  },
  {
    id: "l-4",
    category: "logical",
    subject: "Direction Sense & Vectors",
    difficulty: "Standard",
    question: "A robot starts at point P, moves 12 m North, turns right and moves 9 m East, turns right again and moves 24 m South, and finally turns left and moves 7 m East to point Q. What is the shortest Euclidean distance from P to Q?",
    options: ["20 meters", "18 meters", "25 meters", "16 meters"],
    answer: 0,
    formula: "Distance = sqrt( (Δx)^2 + (Δy)^2 )",
    explanation: "Net East-West displacement Δx = +9 + 7 = +16 m. Net North-South displacement Δy = +12 - 24 = -12 m. Shortest distance = sqrt(16^2 + (-12)^2) = sqrt(256 + 144) = sqrt(400) = 20 meters.",
  },
  {
    id: "l-5",
    category: "logical",
    subject: "Coding & Cryptarithmetic",
    difficulty: "Standard",
    question: "In a certain code language, if 'SYSTEM' is encoded as 'SYSMET' and 'NEARER' is encoded as 'AENRER', how will 'FRACTION' be encoded?",
    options: ["CARFNOIT", "CRAFNOIT", "CARFTION", "FRACNOIT"],
    answer: 0,
    formula: "Split word into two halves of 4 letters and reverse both halves: ABCD EFGH -> DCBA HGFE",
    explanation: "'SYSTEM' (SYS TEM) -> SYS reversed is SYS, TEM reversed is MET => SYSMET. 'NEARER' (NEA RER) -> NEA reversed is AEN, RER reversed is RER => AENRER. 'FRACTION' (FRAC TION) -> FRAC reversed is CARF, TION reversed is NOIT => CARFNOIT.",
  },
  {
    id: "l-6",
    category: "logical",
    subject: "Clocks & Angles",
    difficulty: "Standard",
    question: "What is the acute angle between the hour hand and the minute hand of a clock at 4:20 PM?",
    options: ["10 degrees", "20 degrees", "0 degrees", "15 degrees"],
    answer: 0,
    formula: "Angle θ = |(30 * H) - (5.5 * M)|",
    explanation: "At 4:20, H = 4, M = 20. θ = |(30 * 4) - (5.5 * 20)| = |120 - 110| = 10 degrees.",
  },

  // =========================================================================
  // 3. VERBAL ABILITY & COMPREHENSION (Inference, Error Spotting, Grammar)
  // =========================================================================
  {
    id: "v-1",
    category: "verbal",
    subject: "Sentence Correction & Subject-Verb Agreement",
    difficulty: "Standard",
    question: "Identify the grammatically correct sentence from the choices below:",
    options: [
      "Neither the principal software architect nor the DevOps engineers were available during the production outage.",
      "Neither the principal software architect nor the DevOps engineers was available during the production outage.",
      "Neither the principal software architect or the DevOps engineers were available during the production outage.",
      "Neither the principal software architect nor the DevOps engineers has been available during the production outage.",
    ],
    answer: 0,
    formula: "Rule of Proximity: In 'Neither...nor', verb agrees with the subject closest to it (engineers = plural => were)",
    explanation: "When two subjects are joined by 'neither...nor', the verb agrees in number and person with the nearer subject ('DevOps engineers' is plural, requiring 'were').",
  },
  {
    id: "v-2",
    category: "verbal",
    subject: "Critical Reasoning & Assumptions",
    difficulty: "Standard",
    question: "Statement: 'Backlox provides interactive cloud compilation sandboxes so that aspiring software engineers can build verified proof-of-work repositories.'\nAssumption I: Practical coding implementations demonstrate engineering competency better than passive video watching.\nAssumption II: Cloud compilation eliminates local machine dependency for learners.",
    options: [
      "Both Assumption I and II are implicit",
      "Only Assumption I is implicit",
      "Only Assumption II is implicit",
      "Neither Assumption I nor II is implicit",
    ],
    answer: 0,
    formula: "Premise validation: Interactive sandboxes bridge practical verification (I) and cloud accessibility (II)",
    explanation: "Providing interactive cloud sandboxes directly assumes that hands-on proof-of-work is superior for evaluation (I) and that cloud compilation allows any student to execute code regardless of local hardware (II).",
  },
  {
    id: "v-3",
    category: "verbal",
    subject: "Vocabulary & Semantic Precision",
    difficulty: "Standard",
    question: "Select the word that is most opposite in meaning to 'EPHEMERAL':",
    options: ["Perpetual", "Transient", "Fugacious", "Evadable"],
    answer: 0,
    formula: "Antonym mapping: Ephemeral = short-lived, transient; Opposite = Perpetual, eternal",
    explanation: "'Ephemeral' means lasting for a very short time. Its direct antonym is 'Perpetual' (never ending or changing).",
  },
  {
    id: "v-4",
    category: "verbal",
    subject: "Para Jumbles & Sentence Ordering",
    difficulty: "Competitive",
    question: "Arrange the sentences into a coherent paragraph:\nP: As transformer models scaled past billions of parameters, training costs surged dramatically.\nQ: To mitigate this, parameter-efficient fine-tuning (PEFT) methods like LoRA were introduced.\nR: LoRA decomposes weight updates into low-rank matrices, drastically reducing GPU memory.\nS: Consequently, developers can fine-tune frontier LLMs on consumer hardware.",
    options: ["P-Q-R-S", "Q-P-R-S", "P-R-Q-S", "R-S-P-Q"],
    answer: 0,
    formula: "Cause-Effect Sequence: Problem (P) -> Solution (Q) -> Mechanism (R) -> Outcome (S)",
    explanation: "P establishes the problem (computational scaling). Q introduces the solution (LoRA). R describes the low-rank mechanism. S delivers the practical outcome (consumer hardware fine-tuning).",
  },

  // =========================================================================
  // 4. COMPUTER SCIENCE & TECHNICAL APTITUDE (GATE / Placement / Coding)
  // =========================================================================
  {
    id: "t-1",
    category: "tech",
    subject: "Data Structures & Trees",
    difficulty: "Standard",
    question: "A strictly binary tree (every non-leaf node has exactly 2 children) has 64 leaf nodes. What is the total number of internal (non-leaf) nodes in this tree?",
    options: ["63", "64", "127", "32"],
    answer: 0,
    formula: "In any strictly binary tree: Internal Nodes = Leaves - 1; Total Nodes = 2 * Leaves - 1",
    explanation: "By mathematical induction for strictly binary trees, if L = 64, then Internal Nodes I = L - 1 = 64 - 1 = 63. (Total nodes = 127).",
  },
  {
    id: "t-2",
    category: "tech",
    subject: "Operating Systems & Concurrency",
    difficulty: "Competitive",
    question: "Which of the following is NOT a necessary condition for a deadlock to occur in an operating system?",
    options: [
      "Preemptive scheduling of CPU threads",
      "Mutual exclusion of non-shareable resources",
      "Hold and wait condition",
      "Circular wait graph amongst processes",
    ],
    answer: 0,
    formula: "Coffman Deadlock Conditions: 1. Mutual Exclusion, 2. Hold & Wait, 3. No Preemption, 4. Circular Wait",
    explanation: "The 4 Coffman conditions are: Mutual Exclusion, Hold & Wait, No Preemption, and Circular Wait. If preemption is allowed (preemptive scheduling), deadlocks can be broken and prevented.",
  },
  {
    id: "t-3",
    category: "tech",
    subject: "Database Management & SQL",
    difficulty: "Standard",
    question: "Which SQL query correctly retrieves the 2nd highest salary from an 'Employees' table without using duplicate values?",
    options: [
      "SELECT MAX(salary) FROM Employees WHERE salary < (SELECT MAX(salary) FROM Employees);",
      "SELECT salary FROM Employees ORDER BY salary DESC LIMIT 1 OFFSET 2;",
      "SELECT MIN(salary) FROM Employees WHERE salary > (SELECT MIN(salary) FROM Employees);",
      "SELECT salary FROM Employees GROUP BY salary HAVING COUNT(*) = 2;",
    ],
    answer: 0,
    formula: "Second Highest = Max salary strictly less than absolute maximum salary",
    explanation: "Subquery `SELECT MAX(salary) FROM Employees` gets the maximum salary. The outer query finds the maximum salary strictly smaller than that value, which is guaranteed to be the second highest.",
  },
  {
    id: "t-4",
    category: "tech",
    subject: "Algorithms & Asymptotics",
    difficulty: "Competitive",
    question: "What is the worst-case time complexity of QuickSort when the pivot chosen is always the maximum or minimum element in the array?",
    options: ["O(n^2)", "O(n log n)", "O(n)", "O(log n)"],
    answer: 0,
    formula: "Recurrence: T(n) = T(n-1) + O(n) => Sum_{i=1}^n i = O(n^2)",
    explanation: "When the pivot is the smallest or largest element, partitioning produces unbalanced subproblems of size 0 and (n-1). The recurrence solves to O(n^2).",
  },

  // =========================================================================
  // 5. CLINICAL & MEDICAL SCIENCES (MBBS / NEET PG / Physiology)
  // =========================================================================
  {
    id: "m-1",
    category: "medical",
    subject: "Clinical Cardiology & ECG",
    difficulty: "Expert",
    question: "A 58-year-old male presents with acute crushing retrosternal chest pain. The 12-lead ECG reveals ST-segment elevation in leads II, III, and aVF with reciprocal ST depression in leads I and aVL. Which coronary artery is most likely occluded?",
    options: [
      "Right Coronary Artery (RCA)",
      "Left Anterior Descending (LAD)",
      "Left Circumflex Artery (LCx)",
      "Left Main Coronary Artery (LMCA)",
    ],
    answer: 0,
    formula: "Leads II, III, aVF view the Inferior Myocardial Wall, perfused by the Right Coronary Artery (RCA) in 85-90% of individuals",
    explanation: "ST elevation in leads II, III, and aVF localizes to an acute Inferior Wall Myocardial Infarction (STEMI), supplied by the RCA (or dominant LCx).",
  },
  {
    id: "m-2",
    category: "medical",
    subject: "Biochemistry & Enzymology",
    difficulty: "Competitive",
    question: "In Michaelis-Menten enzyme kinetics, what happens to the apparent Km and Vmax in the presence of a competitive inhibitor?",
    options: [
      "Km increases, Vmax remains unchanged",
      "Km remains unchanged, Vmax decreases",
      "Both Km and Vmax decrease proportionally",
      "Km decreases, Vmax increases",
    ],
    answer: 0,
    formula: "Competitive inhibition: Inhibitor binds to active site. High substrate concentration overcomes inhibitor (Vmax unchanged, apparent Km increases).",
    explanation: "Competitive inhibitors compete with substrate for the active site. Increasing substrate concentration overcomes the inhibitor, so Vmax is unchanged, but higher [S] is needed to reach half Vmax, so Km increases.",
  },

  // =========================================================================
  // 6. COMMERCE, FINANCE & LEGAL REASONING
  // =========================================================================
  {
    id: "c-1",
    category: "commerce",
    subject: "Capital Asset Pricing Model (CAPM)",
    difficulty: "Standard",
    question: "Under the Capital Asset Pricing Model (CAPM), if the risk-free rate is 6%, the expected market return is 14%, and a stock has a Beta of 1.25, what is the required rate of return for the stock?",
    options: ["16.0%", "15.5%", "17.5%", "14.8%"],
    answer: 0,
    formula: "E(R) = Rf + Beta * [E(Rm) - Rf]",
    explanation: "E(R) = 6% + 1.25 * (14% - 6%) = 6% + 1.25 * 8% = 6% + 10% = 16.0%.",
  },
  {
    id: "c-2",
    category: "commerce",
    subject: "Constitutional Law & Jurisprudence",
    difficulty: "Standard",
    question: "In which landmark judgment did the Supreme Court of India propound the 'Basic Structure Doctrine', establishing that Parliament cannot amend the fundamental framework of the Constitution?",
    options: [
      "Kesavananda Bharati v. State of Kerala (1973)",
      "Golaknath v. State of Punjab (1967)",
      "Minerva Mills v. Union of India (1980)",
      "Maneka Gandhi v. Union of India (1978)",
    ],
    answer: 0,
    formula: "Kesavananda Bharati (13-judge bench, 1973) established the inviolability of the Basic Structure under Article 368",
    explanation: "The 13-judge bench in Kesavananda Bharati (1973) ruled that while Parliament has wide powers to amend the Constitution under Article 368, it cannot alter its 'Basic Structure' (democracy, rule of law, separation of powers).",
  },
];
